name: Update legacy meta file
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
 build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Update meta template
        run: |
          rm ./meta.json
          $(cat .\.github\meta.json).Replace("%HASH%", $(.\.github\hash.exe ".\BerserkerBlocker").Substring(17)) > meta.json
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update legacy hash
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: false
